
        package com.ca.directory;
        // automatically generated by ant build.xml file.
        //THIS FILE MUST NOT BE ADDED TO svn OR THE LIVE MAKE SYSTEM
    
        public class BuildNumber
        {
            public static String value = "JXplorer (build JXv3.3.1.2 2024-04-11 09:12 CDT)";
        }
        